### ISSUE TITLE
Lost password flow

### ISSUE THREAD

**Issue by Firesphere** [Firesphere/silverstripe-bootstrapmfa#39] opened 2018-10-30 00:45 UTC
Default flow should include that after the password has been changed, the user enters it's MFA method.

**Comment by robbieaverill** [comment] 2018-11-08 09:09
This came up in sprint planning earlier this week. We looked at how GitHub does this, and decided to follow the same flow. That is that when the user clicks on the link in their email to reset their password, they first have to go through the MFA check, then get to change their password.

I think this might be a duplicate of another issue too

**Comment by robbieaverill** [comment] 2018-11-08 09:10
Ah yep: duplicate of https://github.com/Firesphere/silverstripe-bootstrapmfa/issues/7

**Closed by robbieaverill** 2018-11-08 09:10 UTC
